# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdf_kernel_C <- function(x, X, Ktype, bwd) {
    .Call(`_npThresh_cdf_kernel_C`, x, X, Ktype, bwd)
}

cdf_loocv_kernel_C <- function(x, X, Ktype, bwd, hx) {
    .Call(`_npThresh_cdf_loocv_kernel_C`, x, X, Ktype, bwd, hx)
}

cv_bwd_C <- function(x, X, Ktype, hx, bwd_seq) {
    .Call(`_npThresh_cv_bwd_C`, x, X, Ktype, hx, bwd_seq)
}

PCO_bwd_C <- function(X, Ktype, bwd_seq) {
    .Call(`_npThresh_PCO_bwd_C`, X, Ktype, bwd_seq)
}

cdf_proj_C <- function(x, X, a, b, M) {
    .Call(`_npThresh_cdf_proj_C`, x, X, a, b, M)
}

